# Generated by Django 5.0 on 2023-12-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=100)),
                ('itemgroup', models.CharField(max_length=100)),
                ('unitprice', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('enchantment', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
