# Generated by Django 5.0 on 2023-12-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketPrices',
            new_name='MarketPricesModel',
        ),
    ]
