# Generated by Django 5.0 on 2023-12-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_prices', '0002_rename_marketprices_marketpricesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketpricesmodel',
            old_name='enchantment',
            new_name='EnchantmentLevel',
        ),
        migrations.RenameField(
            model_name='marketpricesmodel',
            old_name='itemgroup',
            new_name='ItemGroupTypeId',
        ),
        migrations.RenameField(
            model_name='marketpricesmodel',
            old_name='unique_name',
            new_name='ItemTypeId',
        ),
        migrations.RenameField(
            model_name='marketpricesmodel',
            old_name='quality',
            new_name='QualityLevel',
        ),
        migrations.RenameField(
            model_name='marketpricesmodel',
            old_name='tier',
            new_name='Tier',
        ),
        migrations.RenameField(
            model_name='marketpricesmodel',
            old_name='unitprice',
            new_name='UnitPriceSilver',
        ),
    ]
