# Generated by Django 5.0 on 2023-12-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_prices', '0003_rename_enchantment_marketpricesmodel_enchantmentlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpricesmodel',
            name='Location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
