# Generated by Django 4.2.8 on 2023-12-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('image_url', models.URLField(default=None)),
                ('weapon_class', models.CharField(max_length=50)),
                ('weapon_category', models.CharField(default=None, max_length=50)),
                ('weapon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='market_api.itemdescriptionmodel')),
            ],
        ),
    ]
