# Generated by Django 4.2.8 on 2023-12-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(default='', max_length=100)),
                ('tier', models.IntegerField()),
                ('image_url', models.URLField(default=None)),
                ('weapon_class', models.CharField(max_length=50)),
            ],
        ),
    ]
