# Generated by Django 4.2.8 on 2023-12-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0003_alter_weaponmodel_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponmodel',
            name='unique_name',
            field=models.CharField(max_length=50),
        ),
    ]
