# Generated by Django 4.2.8 on 2023-12-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0005_weaponmodel_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponmodel',
            name='item_name',
        ),
    ]
