# Generated by Django 5.0 on 2023-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0009_mountmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='weaponmodel',
            name='unique_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
