# Generated by Django 4.2.8 on 2023-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0010_remove_weaponmodel_id_alter_weaponmodel_unique_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('unique_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tier', models.IntegerField()),
                ('image_url', models.URLField(default=None)),
                ('item_class', models.CharField(max_length=50)),
                ('item_category', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MountModel',
        ),
        migrations.DeleteModel(
            name='OffHandModel',
        ),
        migrations.DeleteModel(
            name='WeaponModel',
        ),
    ]
