# Generated by Django 4.2.8 on 2023-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0011_itemmodel_delete_mountmodel_delete_offhandmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_sub_category',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
